UiS.Dat240.Lab3/Pages/Cart.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using UiS.Dat240.Lab3.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using UiS.Dat240.Lab3.Core.Domain.Ordering.Dto;
using System;
using Microsoft.AspNetCore.Http;

namespace UiS.Dat240.Lab3.Pages
{
	public class CartModel : PageModel
	{
		private readonly IMediator _mediator;

		public CartModel(IMediator mediator) => _mediator = mediator ?? throw new System.ArgumentNullException(nameof(mediator));

		public ShoppingCart? Cart { get; private set; }

		public string Building {get; set;} ="";
		public int RoomNumber {get; set;}

		public string NotesBuild {get; set;} ="";
		public string Name {get; set;} = "";
		public string Notes {get; set;} = "";

		public async Task OnGetAsync()
		{
			var cartId = HttpContext.Session.GetGuid("CartId");
			if (cartId is null) return;

			Cart = await _mediator.Send(new Get.Request(cartId.Value));
		}


		//[BindProperty(SupportsGet = true)]
		public async Task<IActionResult> OnPostAsync(string Building, int RoomNumber, string NotesBuild,  string Name){
			//Send shit til iordering dritten og service
			// Console.WriteLine(Building);
			// Console.WriteLine(RoomNumber);
			// Console.WriteLine(NotesBuild);
			// Console.WriteLine(Name);
			// Console.WriteLine(Notes);
			if (Building is null || RoomNumber <= 0 || NotesBuild is null || Name is null){
				return Page();
			}
			var loc = new Core.Domain.Ordering.Location(Building, RoomNumber,NotesBuild);
			var cartId = HttpContext.Session.GetGuid("CartId");
			if (cartId is null) return Page();

			var orderid = await _mediator.Send(new CartCheckout.Request(loc, Name, cartId.Value));

			Console.WriteLine(orderid);

			

			//Core.Domain.Ordering.Services.IOrderingService.PlaceOrder(loc, Name, orderinglines);

			

			//OrderLineDto[] temp = new OrderLineDto[0]();
			
			//var result = await _mediator.Send(new Ordering.Request(loc, Name, orderinglines)); //Fjern notes, legg inn order.lines
			//if (result.Success) return Page();
			//var result = Core.Domain.Ordering.Services.OrderingService.PlaceOrder(loc, Name, orderinglines);

			//Errors = result.Errors;

			cartId = Guid.NewGuid();
			HttpContext.Session.SetString("CartId", cartId.ToString());


			return Page();
			
		}
	}
}
 

UiS.Dat240.Lab3/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace UiS.Dat240.Lab3.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; } = "";

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

UiS.Dat240.Lab3/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Products;
using UiS.Dat240.Lab3.Helpers;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UiS.Dat240.Lab3.Pages
{
	public class IndexModel : PageModel
	{
		private readonly IMediator _mediator;
		public IndexModel(IMediator mediator) => _mediator = mediator;

		public List<FoodItem> FoodItems { get; set; } = new();

		public async Task OnGetAsync()
			=> FoodItems = await _mediator.Send(new Core.Domain.Products.Pipelines.Get.Request());

		public async Task<IActionResult> OnPostAddToCartAsync(int id, string name, decimal price)
		{
			var cartId = HttpContext.Session.GetGuid("CartId");
			if (cartId == null)
			{
				cartId = Guid.NewGuid();
				HttpContext.Session.SetString("CartId", cartId.ToString());
			}

			await _mediator.Send(new Core.Domain.Cart.Pipelines.AddItem.Request(id, name, price, cartId.Value));

			return RedirectToPage();
		}
	}
}

UiS.Dat240.Lab3/Pages/Ordersview.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using UiS.Dat240.Lab3.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using UiS.Dat240.Lab3.Core.Domain.Ordering.Dto;
using UiS.Dat240.Lab3.Core.Domain.Ordering;
using System;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment.Pipelines;
using UiS.Dat240.Lab3.Core.Exceptions;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment;
using UiS.Dat240.Lab3.Infrastructure.Data;
using UiS.Dat240.Lab3.Core.Domain.Products.Events;

namespace UiS.Dat240.Lab3.Pages
{
	public class OrdersviewModel : PageModel
	{
		private readonly IMediator _mediator;

        private readonly ShopContext context;

		public OrdersviewModel(IMediator mediator) => _mediator = mediator ?? throw new System.ArgumentNullException(nameof(mediator));
        public List<Order> _orders { get; set; } = new();
        public List<Offer> _offers {get; set;} = new();
        public string Name {get; set; } ="";
        public int id {get; set; }
        

		public async Task OnGetAsync(){
			_orders = await _mediator.Send(new Core.Domain.Products.Pipelines.GetOrders.Request());
            _offers = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.GetOffers.Request());
        }
        //     try
		// 	{
		// 		var Item = await _mediator.Send(new GetOffer.Request(id));
		// 	}
		// 	catch (EntityNotFoundException)
		// 	{
		// 		Console.WriteLine("Fant ikke offer");
		// 	}

        // }

		//[BindProperty(SupportsGet = true)]


        public async Task<IActionResult> OnPostAsync(int id){
            
            var order = await _mediator.Send(new Core.Domain.Ordering.Pipelines.GetOrder.Request(id));           

            //var ferdig = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.OfferMaker.Request(Name,id));
            //var offer = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.SetShipper.Request(id, Name));
            if(order == null){
                return Page();

            }

            return RedirectToPage($"./SingleOrder/{id}");
            
			
		}

	}
}
 

UiS.Dat240.Lab3/Pages/SingleOrder.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using UiS.Dat240.Lab3.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using UiS.Dat240.Lab3.Core.Domain.Ordering.Dto;
using UiS.Dat240.Lab3.Core.Domain.Ordering;
using System;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment.Pipelines;
using UiS.Dat240.Lab3.Core.Exceptions;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment;
using UiS.Dat240.Lab3.Infrastructure.Data;
using UiS.Dat240.Lab3.Core.Domain.Products.Events;
using UiS.Dat240.Lab3.Core.Domain.Invoicing;

namespace UiS.Dat240.Lab3.Pages
{
	public class SingleOrderModel : PageModel
	{
		private readonly IMediator _mediator;

        private readonly ShopContext context;

		public SingleOrderModel(IMediator mediator) {
        _mediator = mediator ?? throw new System.ArgumentNullException(nameof(mediator));
        }
        public Order _order { get; set; } = new();
        public Offer _offer {get; set;} = new();
        public Invoice _invoice {get; set;} = new();
        public string Name {get; set; } ="";
        public int id {get; set; }
        

		public async Task OnGetAsync(int id){ //Må være getorder
			_order = await _mediator.Send(new Core.Domain.Ordering.Pipelines.GetOrder.Request(id));
            _offer = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.GetOffer.Request(id));
            _invoice = await _mediator.Send(new Core.Domain.Invoicing.Pipelines.GetInvoice.Request(id));
        }


        public async Task<IActionResult> OnPostAsync(string Name, int id){
            Console.WriteLine("Kom inn i shipper ting");
            Console.WriteLine(Name);
            Console.WriteLine(id);
            if (Name is null || id < 0){
                return Page();
            }

            //var ferdig = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.OfferMaker.Request(Name,id));
            var offer = await _mediator.Send(new Core.Domain.Fulfillment.Pipelines.SetShipper.Request(id, Name));
            
            

			return RedirectToPage("Ordersview");
			
		}

	}
}

UiS.Dat240.Lab3/Pages/Cart.cshtml
@page
@model Lab3.Pages.CartModel
@{
	ViewData["Title"] = "Shopping cart";
}

<div class="text-center mt-4">

	<h1 class="display-4 mt-5">Your cart</h1>
	<div class="text-left">
		@if (Model.Cart is null)
		{
			<p>There is nothing in your cart</p>
		}
		else
		{
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Dish</th>
						<th scope="col">Count</th>
						<th scope="col">Price</th>
						<th scope="col">Sum</th>
					</tr>
				</thead>
				<tbody>

					@foreach (var item in Model.Cart.Items)
					{
						<tr>
							<th scope="row">@item.Name</th>
							<td>@item.Count</td>
							<td>@item.Price</td>
							<td>@item.Sum</td>
						</tr>
					}
				</tbody>
			</table>
		}
		<div>
			<h2>Add shipping information</h2>
			<div>
				<form asp-action="PlaceOrder">
					<input type="text" asp-for="Building" placeholder="Building"> 
					<input type="text" asp-for="RoomNumber" placeholder="Roomnumber">
					<input type="text" asp-for="NotesBuild" placeholder="Notes about delivery">
					<input type="text" asp-for="Name" placeholder="Customer name">
					<input type="submit" asp-page-handler="PlaceOrder"
										asp-route-Building="@Model.Building"
										asp-route-RoomNumber="@Model.RoomNumber"
										asp-route-NotesBuild="@Model.NotesBuild"
										asp-route-Name="@Model.Name"
					>
									
				</form>
            </div>
		</div>
	</div>
</div>

UiS.Dat240.Lab3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="post">
<div class="text-center">
    <h1 class="display-4 mt-5">Menu</h1>

    @for (int index = 1; index <= 3; index++)
    {
        <div class="menu">
            <img src="~/img/Menu0@(index).png" />

            <ul>
                @foreach (var item in Model.FoodItems.Skip((index - 1) * 8).Take(8))
                {

                    <li>
                        <div class="header">
                            <h2>@item.Name</h2>
                            <p class="price">Kr @string.Format("{0:#0.00}",item.Price)</p>
                        </div>
                        <div class="body">
                            <div>

                                <p class="text">@item.Description</p>
                                <p class="cooking-time">@item.CookTime min</p>
                            </div>
                            <button type="submit" asp-page-handler="AddToCart"
                                asp-route-id="@item.Id"
                                asp-route-name="@item.Name"
                                asp-route-price="@item.Price.ToString("0..00")"
                                  ><img src="~/img/addToCart.svg" height="20" width="20">
                            </button>
                            
                        </div>
                    </li>
                }
            </ul>
        </div>
    }


</div>
</form>

UiS.Dat240.Lab3/Pages/Ordersview.cshtml
@page
@model Lab3.Pages.OrdersviewModel
@{
	ViewData["Title"] = "Orders";
}

<div class="text-center mt-4">

	<h1 class="display-4 mt-5">All Orders</h1>
	<div class="text-left">
		@if (Model._orders is null)
		{
			<p>There are no orders published</p>
		}
		else
		{
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Id</th>
						<th scope="col">Customer</th>
						<th scope="col">Date</th>
						<th scope="col">Building</th>
                        <th scope="col">RoomNumber</th>
                        <th scope="col">Notes</th>
                        <th scope="col">Status</th>
					</tr>
				</thead>
				<tbody>

					@foreach (var item in Model._orders)
					{
						<tr>
                            <th scope="row"><a asp-page="./SingleOrder" asp-route-id="@item.Id">@item.Id</a></th>
                            @if (item.Customer is not null){
							<td>@item.Customer.Name</td>
                            } else{
                                <td>@item.Customer</td>
                            }
							<td>@item.OrderDate</td>
                            @if (item.Location is null){
                                <td>Validator test</td>
                                <td>validator test</td>
                                <td>validator test</td>
                            } else{
							    <td>@item.Location.Building</td>
                                <td>@item.Location.RoomNumber</td>
                                <td>@item.Location.Notes</td>
                            }
                            <td>@item.Status</td>
                            @* <form asp-action="SetFullfillment">
                                <td><input type="text" asp-for="Name" placeholder="Shipper"></td>
                                <input type="hidden" asp-for="@item.Id"/>
                                <td><input type="submit" asp-page-handler="OrderPlaced" asp-route-shipper="@Model.Name"
                                asp-route-id="@item.Id"></td>
                            </form> *@
                            <td></td>
						</tr>
					}
				</tbody>
			</table>
		}
		<div>
            </div>
		</div>
	</div>
</div>

UiS.Dat240.Lab3/Pages/SingleOrder.cshtml
@page "{id:int}"
@model Lab3.Pages.SingleOrderModel
@{
	ViewData["Title"] = "SingleOrder";
}

<div class="text-center mt-4">

	<h1 class="display-4 mt-5">Order @Model._order.Id</h1>
	<div class="text-left">
		@if (Model._order is null)
		{
			<p>There are no orders published</p>
		}
		else
		{
            <table class="table">
                				<thead>
					<tr>
						<th scope="col">Id</th>
                        <th scope="col">Date</th>
						<th scope="col">Customer</th>
						<th scope="col">Building</th>
                        <th scope="col">RoomNumber</th>
                        <th scope="col">Notes</th>
                        <th scope="col">Status</th>
                        <th scope="col">Shipper</th>
                        <th scope="col">Submit</th>
					</tr>
				</thead>
				<tbody>
                    <tr>
                        <td>@Model._order.Id</td>
                        <td>@Model._order.OrderDate</td>
                        @if (@Model._order.Customer is not null){
							<td>@Model._order.Customer.Name</td>
                            } else{
                                <td>Ingen kunde</td>
                            }
                        <td>@Model._order.Location.Building</td>
                        <td>@Model._order.Location.RoomNumber</td>
                        <td>@Model._order.Location.Notes</td>
                        <td>@Model._order.Status</td>
                        @if (Model._offer.Shipper is null){
                            <form asp-action="SetFullfillment">
                                            <td><input type="text" asp-for="Name" placeholder="Shipper"></td>
                                            <input type="hidden" asp-for="@Model._order.Id"/>
                                            <td><input type="submit" asp-page-handler="OrderPlaceddos" asp-route-shipper="@Model.Name"
                                            asp-route-id="@Model._order.Id"></td>
                                        </form>
                        } else{
                            <td>@Model._offer.Shipper.Name</td>
                        }
					
				</tbody>
            </table>
		}
        @if (Model._order.OrderLines is not null){
            <h1 class="display-4 mt-5">Order items</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Count</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var orderline in Model._order.OrderLines){
                    <tr>
                        
                            <td>@orderline.Item</td>
                            <td>@orderline.Price</td>
                            <td>@orderline.Count</td>
                            <td>@orderline.Amount</td>
                        
                    </tr>
                    }
                </tbody>
            </table>
        }
        @if (Model._invoice is not null){
            <h1 class="display-4 mt-5">Invoice</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">OrderId</th>
                        <th scope="col">Customer</th>
                        <th scope="col">Building</th>
                        <th scope="col">RoomNumber</th>
                        <th scope="col">Notes</th>
                        <th scope="col">Total Amount</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model._invoice.Id</td>
                        <td>@Model._invoice.OrderId</td>
                        <td>@Model._order.Customer.Name</td>
                        <td>@Model._invoice.Address.Building</td>
                        <td>@Model._invoice.Address.RoomNumber</td>
                        <td>@Model._invoice.Address.Notes</td>
                        <td>@Model._invoice.Amount</td>
                        <td>@Model._invoice.Status</td>
                    </tr>
                </tbody>
            </table>
        }
        <h1 class="display-4 mt-5">Offer</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">OrderId</th>
                    <th scope="col">Shipper</th>
                    <th scope="col">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model._offer.OrderId</td>
                    @if (Model._offer.Shipper is null){
                        <td>Shipper not set</td>
                    } else {
                        <td>@Model._offer.Shipper.Name</td>
                    }
                    <td>@Model._offer.Reimbursement.Amount</td>
                </tr>
            </tbody>
        </table>
		<div>
            </div>
		</div>
	</div>
</div>